name: Test

on: push
concurrency: test
jobs:
  test:
    name: Test Server Donation Tool
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm test
